### ISSUE TITLE
Xsens Wired Suit Does Not Calibrate

### ISSUE THREAD

**Issue by kouroshD** [robotology/wearables#69] opened 2019-12-04 10:35 UTC
Yesterday and today we tried a lot of times with different options to calibrate the Xsens suit, but it returns `poor` quality calibration results.  The result with `NposeWalk`, `Tpose` was always poor. The result with `Npose` was some times good, but the visualization result shows the poor result (as following you can see).
We have checked several times the sensor placements and they were correct.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17707730/70135201-dcdca600-1689-11ea-802d-8b8881bf89b6.gif)

**Comment by kouroshD** [comment] 2019-12-04 12:00
The result with frank wearing the Xsens wired suit. The result of the calibration in `Npose` was acceptable with frank.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/17707730/70140851-f1bf3680-1695-11ea-9cc3-09a50400a6e1.gif)

**Comment by lrapetti** [comment] 2019-12-05 08:38
Given that previously we never experienced this, I'm not sure if the problem is related to software or to a failure in the hardware (broken sensors? Wrong connections?)

From the two gif you posted we don't have much information, since the behaviour is somehow normal when the calibration is bad. The only thing that is a bit weird is the rotation of the feet that is quite fast compared to the drift we observed in the past.

**Comment by Yeshasvitvs** [comment] 2019-12-06 08:54
One thing we can do is to try to run the wired suit with either @claudia-lat or @lrapetti and see if the calibration works without problems.

**Comment by Yeshasvitvs** [comment] 2019-12-07 11:37
Another viable solution is to request members who have xsens MVN studio license and try to calibrate the wired suit with it. Hopefully this will provide us more information on the status of the suit e.g., if there is any problem with the hardware.

**Comment by DanielePucci** [comment] 2019-12-17 11:00
@claudia-lat this is a very important issue we are currently having. Please discuss with @Yeshasvitvs @kouroshD @lrapetti and then come up with an action plan to follow and implement, thanks

**Comment by claudia-lat** [comment] 2019-12-19 10:56
[Updating 19/12/19]
After an internal discussion we decided to go for a test with the wired suits with other subjects (e.g., @claudia-lat @lrapetti).  This because the problem has been tested only with @kouroshD since now.

**Comment by DanielePucci** [comment] 2020-01-02 14:56
@claudia-lat any outcome of these tests?

**Comment by claudia-lat** [comment] 2020-01-02 15:02
> @claudia-lat any outcome of these tests?

Actually, the last available day in the lab before Christmas we didn't do the test. We can do the test the first day available with @lrapetti and @Yeshasvitvs

**Comment by Yeshasvitvs** [comment] 2020-02-04 09:29
Today @lrapetti and I tested the wired suit with @isorrentino as the subject. We tried both Npose and NposeWalk calibration and it went will without any problems.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/6505998/73731484-da093a80-4738-11ea-8e7b-e4226d13b718.gif)

CC @DanielePucci @claudia-lat 

@kouroshD can we close this issue now?

**Comment by claudia-lat** [comment] 2020-02-11 10:21
We can close the issue.

**Closed by claudia-lat** 2020-02-11 10:21 UTC
Labels: complexity:hard, component:xsenssuit, priority:high, severity:major

**Comment by DanielePucci** [comment] 2020-02-24 19:30
The fact that it restarted working without any specific fix is a kind of terrifying, bit we accept it

**Comment by Yeshasvitvs** [comment] 2020-06-29 13:25
> The fact that it restarted working without any specific fix is a kind of terrifying

We are experiencing the same problem again

CC @claudia-lat @lrapetti @kouroshD @DanielePucci
